name: Build Bookdown Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - run: Rscript -e 'install.packages(c("bookdown"))'
      - run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
